CREATE TABLE BOOK (
	ID            INTEGER NOT NULL AUTO_INCREMENT,
	TITLE         VARCHAR,
	AUTHOR        VARCHAR,
	COVER         CHAR NOT NULL,
	PUBLISHEDYEAR INTEGER,
	AVAILABLE     BOOLEAN,
	COMMENTS      VARCHAR,
	PRIMARY KEY (ID)
)